"use strict";
const REDS=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const WHEEL_ORDER=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const money=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"});
const state={initial:0,balance:0,selected:2,bets:new Map(),previous:new Map(),history:[],wins:0,losses:0,wagered:0,spinning:false};
const $=id=>document.getElementById(id); const table=$("table");
function color(n){return n===0?"green":REDS.has(n)?"red":"black"}
function secureNumber(){const range=37,limit=Math.floor(0x100000000/range)*range,a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%range}
WHEEL_ORDER.forEach((n,i)=>{const a=i*2*Math.PI/WHEEL_ORDER.length,p=document.createElement("span");p.className=`wheel-number ${color(n)}`;p.textContent=n;p.style.left=`${50+43.3*Math.sin(a)}%`;p.style.top=`${50-43.3*Math.cos(a)}%`;$("wheelNumbers").appendChild(p)});
function addCell(label,key,cls,style=""){const b=document.createElement("button");b.className=`bet-cell ${cls}`;b.textContent=label;b.dataset.bet=key;if(style)b.style.cssText=style;b.addEventListener("click",()=>place(key));b.addEventListener("dragover",e=>{e.preventDefault();b.classList.add("dragover")});b.addEventListener("dragleave",()=>b.classList.remove("dragover"));b.addEventListener("drop",e=>{e.preventDefault();b.classList.remove("dragover");const v=Number(e.dataTransfer.getData("text/plain"));if(v)place(key,v)});table.appendChild(b)}
addCell("0","n:0","green zero");
for(let n=1;n<=36;n++){const col=Math.ceil(n/3)+1;addCell(String(n),`n:${n}`,`${color(n)} n${((n-1)%3)+1}`,`grid-column:${col}`)}
addCell("2:1","c:3","outside","grid-column:14;grid-row:1");addCell("2:1","c:2","outside","grid-column:14;grid-row:2");addCell("2:1","c:1","outside","grid-column:14;grid-row:3");
addCell("1ª dozzina","d:1","dozen","grid-column:2/6");addCell("2ª dozzina","d:2","dozen","grid-column:6/10");addCell("3ª dozzina","d:3","dozen","grid-column:10/14");
addCell("1–18","low","outside","grid-column:2/4");addCell("PARI","even","outside","grid-column:4/6");addCell("ROSSO","red","outside red","grid-column:6/8");addCell("NERO","black","outside black","grid-column:8/10");addCell("DISPARI","odd","outside","grid-column:10/12");addCell("19–36","high","outside","grid-column:12/14");
function addMarker(nums,type,col,row){const key=`g:${nums.join("-")}`,names={"v-split":"Cavallo","h-split":"Cavallo",street:"Terzina",corner:"Carré",sixline:"Sestina"};addCell("",key,`inside-marker ${type}`,`grid-column:${col};grid-row:${row}`);const el=table.lastElementChild;el.title=`${names[type]}: ${nums.join(" – ")}`;el.setAttribute("aria-label",el.title)}
for(let s=0;s<12;s++){const b=s*3+1,c=s+2;addMarker([b,b+1],"v-split",c,2);addMarker([b+1,b+2],"v-split",c,1);addMarker([b,b+1,b+2],"street",c,4);if(s<11){for(let r=0;r<3;r++)addMarker([b+r,b+3+r],"h-split",c,3-r);addMarker([b,b+1,b+3,b+4],"corner",c,2);addMarker([b+1,b+2,b+4,b+5],"corner",c,1);addMarker([b,b+1,b+2,b+3,b+4,b+5],"sixline",c,4)}}
document.querySelectorAll(".chip").forEach(c=>{c.addEventListener("click",()=>selectChip(Number(c.dataset.value)));c.addEventListener("dragstart",e=>e.dataTransfer.setData("text/plain",c.dataset.value))});
function selectChip(v){state.selected=v;document.querySelectorAll(".chip").forEach(c=>c.classList.toggle("selected",Number(c.dataset.value)===v))}
function place(key,value=state.selected){if(state.spinning)return;if(state.balance<value){$("result").textContent="Saldo insufficiente";return}state.balance-=value;state.bets.set(key,(state.bets.get(key)||0)+value);render()}
function totalBet(){return [...state.bets.values()].reduce((a,b)=>a+b,0)}
function render(){$("balance").textContent=money.format(state.balance);$("totalBet").textContent=money.format(totalBet());$("wins").textContent=state.wins;$("losses").textContent=state.losses;$("wagered").textContent=money.format(state.wagered);const p=state.balance-state.initial+totalBet();$("profit").textContent=(p>0?"+":"")+money.format(p);$("profit").className=p>0?"positive":p<0?"negative":"";document.querySelectorAll(".bet-cell").forEach(c=>{c.querySelector(".cell-chip")?.remove();const v=state.bets.get(c.dataset.bet);if(v){const s=document.createElement("span");s.className="cell-chip";s.textContent=v;c.appendChild(s)}});$("repeatBet").disabled=!state.previous.size||state.spinning;$("clearBet").disabled=!state.bets.size||state.spinning;$("spin").disabled=!state.bets.size||state.spinning;$("history").innerHTML=state.history.length?state.history.map(n=>`<span class="history-num ${color(n)}">${n}</span>`).join(""):'<span class="empty">Nessun giro</span>'}
function outcome(key,n){if(key.startsWith("n:"))return Number(key.slice(2))===n?36:0;if(key.startsWith("g:")){const nums=key.slice(2).split("-").map(Number);return nums.includes(n)?36/nums.length:0}if(n===0)return 0;if(key.startsWith("d:")){const d=Number(key.slice(2));return n>=(d-1)*12+1&&n<=d*12?3:0}if(key.startsWith("c:"))return ((n-1)%3)+1===Number(key.slice(2))?3:0;if(key==="low")return n<=18?2:0;if(key==="high")return n>=19?2:0;if(key==="even")return n%2===0?2:0;if(key==="odd")return n%2===1?2:0;if(key==="red")return REDS.has(n)?2:0;if(key==="black")return REDS.has(n)?0:2;return 0}
async function spin(){if(!state.bets.size||state.spinning)return;state.spinning=true;const stake=totalBet(),n=secureNumber();state.wagered+=stake;state.previous=new Map(state.bets);$("result").textContent="La pallina gira…";const track=$("ballTrack"),slot=WHEEL_ORDER.indexOf(n),landing=slot*360/WHEEL_ORDER.length;track.style.transition="none";track.style.transform="rotate(0deg)";void track.offsetWidth;track.style.transition="transform 4s cubic-bezier(.12,.7,.08,1)";track.style.transform=`rotate(${1800+landing}deg)`;$("wheel").classList.add("spinning");$("spin").disabled=true;await new Promise(r=>setTimeout(r,4000));let returned=0;for(const [key,bet] of state.bets)returned+=bet*outcome(key,n);state.balance+=returned;state.bets.clear();state.history.unshift(n);state.history=state.history.slice(0,15);const net=returned-stake,label=`${n} ${color(n)==="red"?"ROSSO":color(n)==="black"?"NERO":"VERDE"}`;if(net>0){state.wins++;$("result").textContent=`${label} — Vinti ${money.format(net)}`}else{state.losses++;$("result").textContent=`${label} — ${net===0?"Pareggio":`Persi ${money.format(-net)}`}`}state.spinning=false;$("wheel").classList.remove("spinning");render()}
$("spin").addEventListener("click",spin);$("clearBet").addEventListener("click",()=>{state.balance+=totalBet();state.bets.clear();$("result").textContent="Puntata ritirata";render()});$("repeatBet").addEventListener("click",()=>{const need=[...state.previous.values()].reduce((a,b)=>a+b,0);if(need>state.balance){$("result").textContent="Saldo insufficiente per ripetere";return}state.bets=new Map(state.previous);state.balance-=need;$("result").textContent="Puntata precedente ripristinata";render()});
function reset(){if(state.spinning)return;state.initial=0;state.balance=0;state.bets.clear();state.previous.clear();state.history=[];state.wins=state.losses=state.wagered=0;$("result").textContent="Piazza le fiches";$("depositDialog").showModal();render()}
$("reset").addEventListener("click",reset);$("depositForm").addEventListener("submit",e=>{e.preventDefault();const v=Math.floor(Number($("deposit").value));if(!Number.isFinite(v)||v<2)return;state.initial=state.balance=v;$("depositDialog").close();render()});
$("depositDialog").addEventListener("cancel",e=>{if(!state.initial)e.preventDefault()});$("depositDialog").showModal();render();
