"use strict";
const money=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}),$=id=>document.getElementById(id);
const suits=["♠","♥","♦","♣"],ranks=["A","2","3","4","5","6","7","8","9","10","J","Q","K"];
const state={shoe:[],player:[],dealer:[],initial:0,balance:0,bet:0,lastBet:0,inRound:false,reveal:false,wins:0,losses:0,pushes:0,wagered:0};
function rand(max){const lim=Math.floor(0x100000000/max)*max,a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=lim);return a[0]%max}
function newShoe(){state.shoe=[];for(let d=0;d<2;d++)for(const suit of suits)for(const rank of ranks)state.shoe.push({rank,suit});for(let i=state.shoe.length-1;i>0;i--){const j=rand(i+1);[state.shoe[i],state.shoe[j]]=[state.shoe[j],state.shoe[i]]}}
function draw(){if(state.shoe.length<1)newShoe();return state.shoe.pop()}
function score(hand){let total=0,aces=0;for(const c of hand){if(c.rank==="A"){total+=11;aces++}else total+=Math.min(10,Number(c.rank)||10)}while(total>21&&aces){total-=10;aces--}return total}
function blackjack(h){return h.length===2&&score(h)===21}
function cardHTML(c,hidden=false){if(hidden)return '<div class="card back" aria-label="Carta coperta"></div>';const red=c.suit==="♥"||c.suit==="♦";return `<div class="card ${red?"red":""}">${c.rank}<span class="suit">${c.suit}</span></div>`}
function render(){$("balance").textContent=money.format(state.balance);$("bet").textContent=money.format(state.bet);$("shoeCount").textContent=state.shoe.length;$("playerCards").innerHTML=state.player.map(c=>cardHTML(c)).join("");$("dealerCards").innerHTML=state.dealer.map((c,i)=>cardHTML(c,!state.reveal&&i===1)).join("");$("playerScore").textContent=state.player.length?score(state.player):"—";$("dealerScore").textContent=state.dealer.length?(state.reveal?score(state.dealer):score([state.dealer[0]])):"—";$("wins").textContent=state.wins;$("losses").textContent=state.losses;$("pushes").textContent=state.pushes;$("wagered").textContent=money.format(state.wagered);const p=state.balance-state.initial;$("profit").textContent=(p>0?"+":"")+money.format(p);$("profit").className=p>0?"positive":p<0?"negative":"";$("deal").disabled=state.inRound||state.bet<2||state.bet>state.balance;$("hit").disabled=!state.inRound;$("stand").disabled=!state.inRound;$("double").disabled=!state.inRound||state.player.length!==2||state.balance<state.bet;$("clearBet").disabled=state.inRound||!state.bet;$("repeatBet").disabled=state.inRound||!state.lastBet||state.lastBet>state.balance}
function settle(kind){state.inRound=false;state.reveal=true;state.lastBet=state.bet;if(kind==="blackjack"){state.balance+=state.bet*2.5;state.wins++;$("message").textContent="BLACK JACK — vincita 3:2"}else if(kind==="win"){state.balance+=state.bet*2;state.wins++;$("message").textContent="Hai vinto"}else if(kind==="push"){state.balance+=state.bet;state.pushes++;$("message").textContent="Pareggio"}else{state.losses++;$("message").textContent="Vince il banco"}state.bet=0;render()}
function deal(){if(state.inRound||state.bet<2||state.bet>state.balance)return;if(state.shoe.length<30)newShoe();state.balance-=state.bet;state.wagered+=state.bet;state.player=[draw(),draw()];state.dealer=[draw(),draw()];state.inRound=true;state.reveal=false;$("message").textContent="Carta o stai?";if(blackjack(state.player)||blackjack(state.dealer)){state.reveal=true;if(blackjack(state.player)&&blackjack(state.dealer))settle("push");else if(blackjack(state.player))settle("blackjack");else settle("lose")}render()}
function hit(){if(!state.inRound)return;state.player.push(draw());if(score(state.player)>21){state.reveal=true;settle("lose")}else render()}
function stand(){if(!state.inRound)return;state.reveal=true;while(score(state.dealer)<17)state.dealer.push(draw());const p=score(state.player),d=score(state.dealer);settle(d>21||p>d?"win":p===d?"push":"lose")}
function doubleDown(){if(!state.inRound||state.player.length!==2||state.balance<state.bet)return;state.balance-=state.bet;state.wagered+=state.bet;state.bet*=2;state.player.push(draw());if(score(state.player)>21){state.reveal=true;settle("lose")}else stand()}
document.querySelectorAll(".chip").forEach(b=>b.addEventListener("click",()=>{const v=Number(b.dataset.value);if(!state.inRound&&state.bet+v<=state.balance){state.bet+=v;render()}}));$("deal").addEventListener("click",deal);$("hit").addEventListener("click",hit);$("stand").addEventListener("click",stand);$("double").addEventListener("click",doubleDown);$("clearBet").addEventListener("click",()=>{state.bet=0;render()});$("repeatBet").addEventListener("click",()=>{if(!state.inRound&&state.lastBet<=state.balance){state.bet=state.lastBet;render()}});
function reset(){state.initial=state.balance=state.bet=state.lastBet=0;state.player=[];state.dealer=[];state.inRound=false;state.reveal=false;state.wins=state.losses=state.pushes=state.wagered=0;newShoe();$("message").textContent="Scegli la puntata e distribuisci";$("depositDialog").showModal();render()}$("reset").addEventListener("click",reset);$("depositForm").addEventListener("submit",e=>{e.preventDefault();const v=Math.floor(Number($("deposit").value));if(!Number.isFinite(v)||v<2)return;state.initial=state.balance=v;$("depositDialog").close();render()});newShoe();$("depositDialog").showModal();render();
