"use strict";
const money=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}),$=id=>document.getElementById(id);
const suits=["♠","♥","♦","♣"],ranks=["A","2","3","4","5","6","7","8","9","10","J","Q","K"];
const state={shoe:[],hands:[],handBets:[],dealer:[],activeHand:0,initial:0,balance:0,bet:0,lastBet:0,inRound:false,reveal:false,wins:0,losses:0,pushes:0,wagered:0,splitRound:false};
function rand(max){const lim=Math.floor(0x100000000/max)*max,a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=lim);return a[0]%max}
function newShoe(){state.shoe=[];for(let d=0;d<2;d++)for(const suit of suits)for(const rank of ranks)state.shoe.push({rank,suit});for(let i=state.shoe.length-1;i>0;i--){const j=rand(i+1);[state.shoe[i],state.shoe[j]]=[state.shoe[j],state.shoe[i]]}}
function draw(){if(!state.shoe.length)newShoe();return state.shoe.pop()}
function value(c){return c.rank==="A"?11:Math.min(10,Number(c.rank)||10)}
function score(hand){let total=0,aces=0;for(const c of hand){total+=value(c);if(c.rank==="A")aces++}while(total>21&&aces){total-=10;aces--}return total}
function blackjack(h){return h.length===2&&score(h)===21}
function cardHTML(c,hidden=false){if(hidden)return '<playing-card class="real-card" cid="00" backcolor="#172c50" bordercolor="#f4ecd9" borderline="4" borderradius="10" aria-label="Carta coperta"></playing-card>';const suitCode={"♠":"s","♥":"h","♦":"d","♣":"c"}[c.suit],rankCode=c.rank==="10"?"T":c.rank;return `<playing-card class="real-card" cid="${rankCode}${suitCode}" opacity="1" bordercolor="#e8e8e8" borderline="2" borderradius="10" aria-label="${c.rank} di ${c.suit}"></playing-card>`}
function current(){return state.hands[state.activeHand]||[]}
function canSplit(){const h=current();return state.inRound&&state.hands.length===1&&h.length===2&&value(h[0])===value(h[1])&&state.balance>=state.handBets[0]}
function playerHTML(){if(state.hands.length<2)return (state.hands[0]||[]).map(c=>cardHTML(c)).join("");return `<div class="split-hands">${state.hands.map((h,i)=>`<div class="split-hand ${state.inRound&&i===state.activeHand?"active":""}"><span class="split-label">MANO ${i+1} · ${score(h)}</span><div class="cards">${h.map(c=>cardHTML(c)).join("")}</div></div>`).join("")}</div>`}
function render(){const totalBet=state.inRound?state.handBets.reduce((a,b)=>a+b,0):state.bet;$("balance").textContent=money.format(state.balance);$("bet").textContent=money.format(totalBet);$("shoeCount").textContent=state.shoe.length;$("playerCards").innerHTML=playerHTML();$("dealerCards").innerHTML=state.dealer.map((c,i)=>cardHTML(c,!state.reveal&&i===1)).join("");$("playerScore").textContent=state.hands.length?(state.hands.length===1?score(state.hands[0]):state.hands.map(score).join(" / ")):"—";$("dealerScore").textContent=state.dealer.length?(state.reveal?score(state.dealer):score([state.dealer[0]])):"—";$("wins").textContent=state.wins;$("losses").textContent=state.losses;$("pushes").textContent=state.pushes;$("wagered").textContent=money.format(state.wagered);const p=state.balance-state.initial;$("profit").textContent=(p>0?"+":"")+money.format(p);$("profit").className=p>0?"positive":p<0?"negative":"";$("deal").disabled=state.inRound||state.bet<2||state.bet>state.balance;$("hit").disabled=!state.inRound;$("stand").disabled=!state.inRound;$("double").disabled=!state.inRound||current().length!==2||state.balance<state.handBets[state.activeHand];$("split").disabled=!canSplit();$("clearBet").disabled=state.inRound||!state.bet;$("repeatBet").disabled=state.inRound||!state.lastBet||state.lastBet>state.balance}
function finishNatural(kind){state.inRound=false;state.reveal=true;state.lastBet=state.bet;if(kind==="blackjack"){state.balance+=state.bet*2.5;state.wins++;$("message").textContent="BLACK JACK — vincita 3:2"}else if(kind==="push"){state.balance+=state.bet;state.pushes++;$("message").textContent="Pareggio"}else{state.losses++;$("message").textContent="Black Jack del banco"}state.bet=0;render()}
function resolveRound(){state.reveal=true;while(score(state.dealer)<17)state.dealer.push(draw());const d=score(state.dealer),results=[];state.hands.forEach((h,i)=>{const p=score(h),stake=state.handBets[i];if(p>21){state.losses++;results.push(`Mano ${i+1}: persa`)}else if(d>21||p>d){state.balance+=stake*2;state.wins++;results.push(`Mano ${i+1}: vinta`)}else if(p===d){state.balance+=stake;state.pushes++;results.push(`Mano ${i+1}: pareggio`)}else{state.losses++;results.push(`Mano ${i+1}: persa`)}});state.inRound=false;state.lastBet=state.bet;state.bet=0;$("message").textContent=state.hands.length>1?results.join(" · "):results[0].replace("Mano 1: ","");render()}
function nextHand(){if(state.activeHand<state.hands.length-1){state.activeHand++;$("message").textContent=`Gioca la mano ${state.activeHand+1}`;render()}else resolveRound()}
function deal(){if(state.inRound||state.bet<2||state.bet>state.balance)return;if(state.shoe.length<30)newShoe();state.balance-=state.bet;state.wagered+=state.bet;state.hands=[[draw(),draw()]];state.handBets=[state.bet];state.dealer=[draw(),draw()];state.activeHand=0;state.splitRound=false;state.inRound=true;state.reveal=false;$("message").textContent="Carta, stai, raddoppia o split?";if(blackjack(state.hands[0])||blackjack(state.dealer)){state.reveal=true;if(blackjack(state.hands[0])&&blackjack(state.dealer))finishNatural("push");else if(blackjack(state.hands[0]))finishNatural("blackjack");else finishNatural("lose")}render()}
function hit(){if(!state.inRound)return;current().push(draw());if(score(current())>=21)nextHand();else render()}
function stand(){if(state.inRound)nextHand()}
function doubleDown(){if(!state.inRound||current().length!==2)return;const stake=state.handBets[state.activeHand];if(state.balance<stake)return;state.balance-=stake;state.wagered+=stake;state.handBets[state.activeHand]*=2;current().push(draw());nextHand()}
function split(){if(!canSplit())return;const stake=state.handBets[0],cards=state.hands[0];state.balance-=stake;state.wagered+=stake;state.hands=[[cards[0],draw()],[cards[1],draw()]];state.handBets=[stake,stake];state.activeHand=0;state.splitRound=true;$("message").textContent="Gioca la mano 1";render()}
document.querySelectorAll(".chip").forEach(b=>b.addEventListener("click",()=>{const v=Number(b.dataset.value);if(!state.inRound&&state.bet+v<=state.balance){state.bet+=v;render()}}));$("deal").addEventListener("click",deal);$("hit").addEventListener("click",hit);$("stand").addEventListener("click",stand);$("double").addEventListener("click",doubleDown);$("split").addEventListener("click",split);$("clearBet").addEventListener("click",()=>{state.bet=0;render()});$("repeatBet").addEventListener("click",()=>{if(!state.inRound&&state.lastBet<=state.balance){state.bet=state.lastBet;render()}});
function reset(){state.initial=state.balance=state.bet=state.lastBet=0;state.hands=[];state.handBets=[];state.dealer=[];state.activeHand=0;state.inRound=false;state.reveal=false;state.wins=state.losses=state.pushes=state.wagered=0;newShoe();$("message").textContent="Scegli la puntata e distribuisci";$("depositDialog").showModal();render()}$("reset").addEventListener("click",reset);$("depositForm").addEventListener("submit",e=>{e.preventDefault();const v=Math.floor(Number($("deposit").value));if(!Number.isFinite(v)||v<2)return;state.initial=state.balance=v;$("depositDialog").close();render()});newShoe();$("depositDialog").showModal();render();
