"use strict";
const REDS=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const money=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}),pct=new Intl.NumberFormat("it-IT",{style:"percent",minimumFractionDigits:2,maximumFractionDigits:2}),$=id=>document.getElementById(id);
const definitions={
straight:{label:"Pieno",count:1},split:{label:"Cavallo",count:2},street:{label:"Terzina",count:3},corner:{label:"Carré",count:4},sixline:{label:"Sestina",count:6},
dozen1:{label:"1ª dozzina",set:n=>n>=1&&n<=12,gross:3},dozen2:{label:"2ª dozzina",set:n=>n>=13&&n<=24,gross:3},dozen3:{label:"3ª dozzina",set:n=>n>=25&&n<=36,gross:3},
column1:{label:"1ª colonna",set:n=>n>0&&(n-1)%3===0,gross:3},column2:{label:"2ª colonna",set:n=>n>0&&(n-1)%3===1,gross:3},column3:{label:"3ª colonna",set:n=>n>0&&(n-1)%3===2,gross:3},
red:{label:"Rosso",set:n=>REDS.has(n),gross:2},black:{label:"Nero",set:n=>n>0&&!REDS.has(n),gross:2},even:{label:"Pari",set:n=>n>0&&n%2===0,gross:2},odd:{label:"Dispari",set:n=>n%2===1,gross:2},low:{label:"1–18",set:n=>n>=1&&n<=18,gross:2},high:{label:"19–36",set:n=>n>=19&&n<=36,gross:2}};
function color(n){return n===0?"green":REDS.has(n)?"red":"black"}
function secureNumbers(count){const out=[],limit=Math.floor(0x100000000/37)*37;while(out.length<count){const a=new Uint32Array(Math.min(65536,count-out.length+1024));crypto.getRandomValues(a);for(const v of a){if(v<limit){out.push(v%37);if(out.length===count)break}}}return out}
function validInside(type,nums){const a=[...nums].sort((x,y)=>x-y);if(type==="straight")return true;if(a.includes(0))return false;if(type==="split")return(a[1]-a[0]===1&&Math.ceil(a[0]/3)===Math.ceil(a[1]/3))||a[1]-a[0]===3;if(type==="street")return a[0]%3===1&&a[1]===a[0]+1&&a[2]===a[0]+2;if(type==="corner")return(a[0]%3===1||a[0]%3===2)&&a[1]===a[0]+1&&a[2]===a[0]+3&&a[3]===a[0]+4;if(type==="sixline")return a[0]%3===1&&a.every((n,i)=>n===a[0]+i);return false}
function parseBet(){const type=$("betType").value,d=definitions[type];if(d.count){const nums=$("numbers").value.split(/[ ,;/-]+/).filter(Boolean).map(Number),unique=[...new Set(nums)];if(unique.length!==d.count||unique.some(n=>!Number.isInteger(n)||n<0||n>36))throw new Error(d.label+": inserisci "+d.count+" "+(d.count===1?"numero":"numeri")+" distinti tra 0 e 36");if(!validInside(type,unique))throw new Error("I numeri indicati non formano un "+d.label.toLowerCase()+" valido sul tavolo");return{label:d.label+" "+unique.join("–"),wins:n=>unique.includes(n),gross:36/d.count,prob:d.count/37}}return{label:d.label,wins:d.set,gross:d.gross,prob:type.startsWith("dozen")||type.startsWith("column")?12/37:18/37}}
function updateBetUI(){const d=definitions[$("betType").value],label=$("numbersLabel");label.hidden=!d.count;if(d.count){label.firstChild.textContent=d.count===1?"Numero scelto":"Numeri scelti ("+d.count+")";$("numbers").placeholder=d.count===1?"Esempio: 17":"Inserisci "+d.count+" numeri separati da virgole";try{const b=parseBet();$("theoretical").textContent=pct.format(b.prob);$("payout").textContent="Pagamento netto: "+(b.gross-1)+":1"}catch{$("theoretical").textContent=pct.format(d.count/37);$("payout").textContent="Pagamento netto: "+(36/d.count-1)+":1"}}else{const probability=String($("betType").value).startsWith("dozen")||String($("betType").value).startsWith("column")?12/37:18/37;$("theoretical").textContent=pct.format(probability);$("payout").textContent="Pagamento netto: "+(d.gross-1)+":1"}}
function playSequence(capital,stake,spins,bet,numbers){let balance=capital,wins=0,losses=0,won=0,lost=0,played=0,ruined=false;const history=[capital],outcomes=[];for(let i=0;i<spins;i++){if(balance<stake){ruined=true;break}const n=numbers[i];outcomes.push(n);played++;if(bet.wins(n)){const profit=stake*(bet.gross-1);balance+=profit;won+=profit;wins++}else{balance-=stake;lost+=stake;losses++}history.push(balance)}return{balance,wins,losses,won,lost,played,ruined,history,outcomes}}
function drawChart(values){const line=$("chartLine"),w=900,h=225,min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min);line.setAttribute("points",values.map((v,i)=>(i*w/Math.max(1,values.length-1))+","+(h-(v-min)*h/range)).join(" "));$("chartRange").textContent=money.format(min)+" — "+money.format(max)}
function showMain(r,capital,spins,bet,stake){$("reportTitle").textContent=bet.label+" · "+money.format(stake)+" per giro";$("turns").textContent=r.played+" / "+spins;$("wins").textContent=r.wins;$("losses").textContent=r.losses;$("wonEuro").textContent=money.format(r.won);$("lostEuro").textContent=money.format(r.lost);$("finalBalance").textContent=money.format(r.balance);const net=r.balance-capital;$("net").textContent=(net>0?"+":"")+money.format(net);$("net").className=net>0?"positive":net<0?"negative":"";$("observed").textContent=pct.format(r.played?r.wins/r.played:0);$("lastNumbers").innerHTML=r.outcomes.slice(-15).map(n=>'<b class="'+color(n)+'">'+n+"</b>").join("");drawChart(r.history)}
async function estimateRuin(capital,stake,spins,bet){const sessions=3000,batch=60;let ruined=0;for(let start=0;start<sessions;start+=batch){const size=Math.min(batch,sessions-start),random=secureNumbers(size*spins);for(let s=0;s<size;s++){let balance=capital;for(let i=0;i<spins;i++){if(balance<stake){ruined++;break}const n=random[s*spins+i];balance+=bet.wins(n)?stake*(bet.gross-1):-stake}}$("status").textContent="Monte Carlo "+Math.min(start+size,sessions).toLocaleString("it-IT")+" / "+sessions.toLocaleString("it-IT");await new Promise(requestAnimationFrame)}return ruined/sessions}
$("simulationForm").addEventListener("submit",async e=>{e.preventDefault();const capital=Number($("capital").value),stake=Number($("stake").value),spins=Number($("spins").value);if(!Number.isFinite(capital)||!Number.isFinite(stake)||capital<2||stake<1){alert("Controlla capitale e puntata");return}if(stake>capital){alert("La puntata non può superare il capitale iniziale");return}let bet;try{bet=parseBet()}catch(err){alert(err.message);return}$("run").disabled=true;$("ruinProbability").textContent="Calcolo…";$("status").textContent="Sequenza in corso";const main=playSequence(capital,stake,spins,bet,secureNumbers(spins));showMain(main,capital,spins,bet,stake);const ruin=await estimateRuin(capital,stake,spins,bet);$("ruinProbability").textContent=pct.format(ruin);$("status").textContent=main.ruined?"Capitale esaurito":"Completata";$("run").disabled=false});
$("betType").addEventListener("change",updateBetUI);$("numbers").addEventListener("input",updateBetUI);updateBetUI();$("finalBalance").textContent=money.format(Number($("capital").value));
