"use strict";
const REDS=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]),money=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}),pct=new Intl.NumberFormat("it-IT",{style:"percent",minimumFractionDigits:2,maximumFractionDigits:2}),$=id=>document.getElementById(id);
const state={selected:2,bets:new Map(),placements:[],running:false},table=$("table");
function color(n){return n===0?"green":REDS.has(n)?"red":"black"}
function secureNumbers(count){const out=[],limit=Math.floor(0x100000000/37)*37;while(out.length<count){const a=new Uint32Array(Math.min(65536,count-out.length+1024));crypto.getRandomValues(a);for(const v of a){if(v<limit){out.push(v%37);if(out.length===count)break}}}return out}
function addCell(label,key,cls,style){const b=document.createElement("button");b.type="button";b.className="bet-cell "+cls;b.textContent=label;b.dataset.bet=key;if(style)b.style.cssText=style;b.addEventListener("click",()=>place(key));b.addEventListener("dragover",e=>{e.preventDefault();b.classList.add("dragover")});b.addEventListener("dragleave",()=>b.classList.remove("dragover"));b.addEventListener("drop",e=>{e.preventDefault();b.classList.remove("dragover");const v=Number(e.dataTransfer.getData("text/plain"));if(v)place(key,v)});table.appendChild(b)}
function addMarker(nums,type,col,row){const names={"v-split":"Cavallo","h-split":"Cavallo",street:"Terzina",corner:"Carré",sixline:"Sestina"},key="g:"+nums.join("-");addCell("",key,"inside-marker "+type,"grid-column:"+col+";grid-row:"+row);const el=table.lastElementChild;el.title=names[type]+": "+nums.join(" – ");el.setAttribute("aria-label",el.title)}
addCell("0","n:0","green zero");for(let n=1;n<=36;n++){const col=Math.ceil(n/3)+1;addCell(String(n),"n:"+n,color(n)+" n"+(((n-1)%3)+1),"grid-column:"+col)}
addCell("2:1","c:3","outside","grid-column:14;grid-row:1");addCell("2:1","c:2","outside","grid-column:14;grid-row:2");addCell("2:1","c:1","outside","grid-column:14;grid-row:3");addCell("1ª dozzina","d:1","dozen","grid-column:2/6");addCell("2ª dozzina","d:2","dozen","grid-column:6/10");addCell("3ª dozzina","d:3","dozen","grid-column:10/14");addCell("1–18","low","outside","grid-column:2/4");addCell("PARI","even","outside","grid-column:4/6");addCell("ROSSO","red","outside red","grid-column:6/8");addCell("NERO","black","outside black","grid-column:8/10");addCell("DISPARI","odd","outside","grid-column:10/12");addCell("19–36","high","outside","grid-column:12/14");
for(let s=0;s<12;s++){const b=s*3+1,c=s+2;addMarker([b,b+1],"v-split",c,2);addMarker([b+1,b+2],"v-split",c,1);addMarker([b,b+1,b+2],"street",c,4);if(s<11){for(let r=0;r<3;r++)addMarker([b+r,b+3+r],"h-split",c,3-r);addMarker([b,b+1,b+3,b+4],"corner",c,2);addMarker([b+1,b+2,b+4,b+5],"corner",c,1);addMarker([b,b+1,b+2,b+3,b+4,b+5],"sixline",c,4)}}
function totalBase(bets=state.bets){return[...bets.values()].reduce((a,b)=>a+b,0)}
function betName(key){if(key.startsWith("n:"))return"Numero "+key.slice(2);if(key.startsWith("g:"))return"Gruppo "+key.slice(2).replaceAll("-","–");if(key.startsWith("d:"))return key.slice(2)+"ª dozzina";if(key.startsWith("c:"))return key.slice(2)+"ª colonna";return{low:"1–18",high:"19–36",even:"Pari",odd:"Dispari",red:"Rosso",black:"Nero"}[key]}
function place(key,value=state.selected){if(state.running)return;state.bets.set(key,(state.bets.get(key)||0)+value);state.placements.push({key,value});renderBets()}
function renderBets(){document.querySelectorAll(".bet-cell").forEach(c=>{const old=c.querySelector(".cell-chip");if(old)old.remove();const v=state.bets.get(c.dataset.bet);if(v){const s=document.createElement("span");s.className="cell-chip";s.textContent=v;c.appendChild(s)}});$("baseTotal").textContent=money.format(totalBase());$("betDescription").textContent=state.bets.size?[...state.bets].map(([k,v])=>betName(k)+" "+money.format(v)).join(" · "):"Nessuna puntata sul tavolo";$("undoBet").disabled=!state.placements.length||state.running;$("clearBet").disabled=!state.bets.size||state.running}
function outcome(key,n){if(key.startsWith("n:"))return Number(key.slice(2))===n?36:0;if(key.startsWith("g:")){const nums=key.slice(2).split("-").map(Number);return nums.includes(n)?36/nums.length:0}if(n===0)return 0;if(key.startsWith("d:")){const d=Number(key.slice(2));return n>=(d-1)*12+1&&n<=d*12?3:0}if(key.startsWith("c:"))return((n-1)%3)+1===Number(key.slice(2))?3:0;if(key==="low")return n<=18?2:0;if(key==="high")return n>=19?2:0;if(key==="even")return n%2===0?2:0;if(key==="odd")return n%2===1?2:0;if(key==="red")return REDS.has(n)?2:0;if(key==="black")return REDS.has(n)?0:2;return 0}
function roundNet(bets,n,factor){let returned=0;for(const[key,amount]of bets)returned+=amount*factor*outcome(key,n);return returned-totalBase(bets)*factor}
function nextProgress(strategy,progress,net){if(net>0)return 0;if(net===0)return progress;if(strategy==="flat")return 0;return progress+1}
function factorFor(strategy,progress){if(strategy==="flat")return 1;if(strategy==="martingale")return 2**progress;let a=1,b=2;if(progress===0)return 1;if(progress===1)return 2;for(let i=2;i<=progress;i++){const c=a+b;a=b;b=c}return b}
function playSequence(capital,spins,strategy,bets,numbers){let balance=capital,progress=0,wins=0,losses=0,pushes=0,won=0,lost=0,played=0,ruined=false,maxStake=0;const history=[capital],outcomes=[];for(let i=0;i<spins;i++){const factor=factorFor(strategy,progress),stake=totalBase(bets)*factor;if(stake>balance){ruined=true;break}maxStake=Math.max(maxStake,stake);const n=numbers[i],net=roundNet(bets,n,factor);balance+=net;outcomes.push(n);played++;if(net>0){wins++;won+=net}else if(net<0){losses++;lost-=net}else pushes++;progress=nextProgress(strategy,progress,net);history.push(balance)}return{balance,wins,losses,pushes,won,lost,played,ruined,maxStake,history,outcomes}}
function theoreticalSuccess(bets){let wins=0;for(let n=0;n<37;n++)if(roundNet(bets,n,1)>0)wins++;return wins/37}
let chartValues=[],chartPoints=[];function drawChart(values){const line=$("chartLine"),left=58,right=890,top=15,bottom=210,min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min);chartValues=values;chartPoints=values.map((v,i)=>({x:left+i*(right-left)/Math.max(1,values.length-1),y:bottom-(v-min)*(bottom-top)/range}));line.setAttribute("points",chartPoints.map(p=>p.x+","+p.y).join(" "));$("yMax").textContent=money.format(max);$("yMid").textContent=money.format((min+max)/2);$("yMin").textContent=money.format(min);$("chartRange").textContent="Min "+money.format(min)+" · Max "+money.format(max)+" · Finale "+money.format(values[values.length-1])}
function showMain(r,capital,spins,strategy,bets){const names={flat:"Puntata invariata",martingale:"Raddoppio",fibonacci:"Fibonacci"};$("reportTitle").textContent=names[strategy]+" · base "+money.format(totalBase(bets));$("turns").textContent=r.played+" / "+spins;$("wins").textContent=r.wins;$("losses").textContent=r.losses;$("pushes").textContent=r.pushes;$("wonEuro").textContent=money.format(r.won);$("lostEuro").textContent=money.format(r.lost);$("maxStake").textContent=money.format(r.maxStake);$("finalBalance").textContent=money.format(r.balance);const net=r.balance-capital;$("net").textContent=(net>0?"+":"")+money.format(net);$("net").className=net>0?"positive":net<0?"negative":"";$("observed").textContent=pct.format(r.played?r.wins/r.played:0);$("theoreticalSuccess").textContent=pct.format(theoreticalSuccess(bets));$("lastNumbers").innerHTML=r.outcomes.slice(-15).map(n=>'<b class="'+color(n)+'">'+n+"</b>").join("");drawChart(r.history)}
async function estimateRuin(capital,spins,strategy,bets){const sessions=5000,batch=50;let ruined=0;for(let start=0;start<sessions;start+=batch){const size=Math.min(batch,sessions-start),random=secureNumbers(size*spins);for(let s=0;s<size;s++){let balance=capital,progress=0;for(let i=0;i<spins;i++){const factor=factorFor(strategy,progress),stake=totalBase(bets)*factor;if(stake>balance){ruined++;break}const net=roundNet(bets,random[s*spins+i],factor);balance+=net;progress=nextProgress(strategy,progress,net)}}$("status").textContent="Monte Carlo "+Math.min(start+size,sessions).toLocaleString("it-IT")+" / "+sessions.toLocaleString("it-IT");await new Promise(requestAnimationFrame)}return ruined/sessions}
document.querySelectorAll(".chip").forEach(c=>{c.addEventListener("click",()=>{state.selected=Number(c.dataset.value);document.querySelectorAll(".chip").forEach(x=>x.classList.toggle("selected",x===c))});c.addEventListener("dragstart",e=>e.dataTransfer.setData("text/plain",c.dataset.value))});
$("undoBet").addEventListener("click",()=>{const last=state.placements.pop();if(!last)return;const value=state.bets.get(last.key)-last.value;if(value)state.bets.set(last.key,value);else state.bets.delete(last.key);renderBets()});$("clearBet").addEventListener("click",()=>{if(state.running)return;state.bets.clear();state.placements=[];renderBets()});
$("simulationForm").addEventListener("submit",async e=>{e.preventDefault();const capital=Number($("capital").value),spins=Number($("spins").value),strategy=$("strategy").value;if(!Number.isFinite(capital)||capital<2){alert("Controlla il capitale iniziale");return}if(!state.bets.size){alert("Metti almeno una fiche sul tavolo");return}const snapshot=new Map(state.bets);if(totalBase(snapshot)>capital){alert("La puntata base supera il capitale iniziale");return}state.running=true;$("run").disabled=true;renderBets();$("ruinProbability").textContent="Calcolo…";$("status").textContent="Sequenza in corso";const main=playSequence(capital,spins,strategy,snapshot,secureNumbers(spins));showMain(main,capital,spins,strategy,snapshot);const ruin=await estimateRuin(capital,spins,strategy,snapshot);$("ruinProbability").textContent=pct.format(ruin);$("status").textContent=main.ruined?"Capitale esaurito":"Completata";state.running=false;$("run").disabled=false;renderBets()});
$("finalBalance").textContent=money.format(Number($("capital").value));renderBets();
function showChartValue(event){if(!chartValues.length)return;const chart=$("chart"),rect=chart.getBoundingClientRect(),svgX=(event.clientX-rect.left)*900/rect.width,left=58,right=890,index=Math.max(0,Math.min(chartValues.length-1,Math.round((svgX-left)/(right-left)*(chartValues.length-1)))),point=chartPoints[index],hover=$("chartHover"),tip=$("chartTooltip");$("hoverLine").setAttribute("x1",point.x);$("hoverLine").setAttribute("x2",point.x);$("hoverDot").setAttribute("cx",point.x);$("hoverDot").setAttribute("cy",point.y);hover.hidden=false;tip.textContent="Giro "+index+" · Saldo "+money.format(chartValues[index]);tip.style.left=(point.x/9)+"%";tip.style.top=(point.y/2.3)+"%";tip.hidden=false}
$("chart").addEventListener("pointermove",showChartValue);$("chart").addEventListener("pointerdown",showChartValue);$("chart").addEventListener("pointerleave",()=>{$("chartHover").hidden=true;$("chartTooltip").hidden=true});
